<?php

namespace App\Controllers;

use CodeIgniter\Exceptions\AlertError;
use CodeIgniter\Exceptions\PageNotFoundException;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class Board extends BaseController
{
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
        helper('alert');
    }

    public function getIndex()
    {
        return view('board_list');
    }

    // url
//    public function reRoute()
//    {
//        $segments = $this->request->getUri()->getSegments();
//
//        $method =ucfirst($segments[1]);
//        if($method ==='Write')
//        {
//            if(isset($segments[2]) && is_numeric($segments[2]))
//            {
//                return $this->Delete($segments[2]);
//            }else{
//                return $this->write();
//            }
//        }
//
//        for($i=0; $i < 3; $i++ ){
//            array_shift($segments); //클레스 뻬고
//        }
//
//
//        if(is_array($segments) && count($segments) > 0){
//            $params = $segments;
//        }else{
//            $params =[];
//        }
//
//        if(method_exists($this,$method)){
//            return call_user_func_array([$this,$method],$params);
//        }else{
//            throw PageNotFoundException::forMethodNotFound($method);
//        }
//
//    }

    public function getWrite()
    {

        return view('welcome_message');
    }
    public function Modify()
    {
        $did = $this->request->getGet('did');
        if(!isset($did) || (int) $did === 0){
            return  Alert('필수 글번호가 없습니다.',true);
        }

        return view('board_write_v');
    }
    
    public function Delete($did)
    {

        echo '삭제('.$did.')';
    }
}
